package remediate

import (
	"strings"
	"testing"

	"github.com/ClatTribe/tsengine/pkg/platform"
	"github.com/ClatTribe/tsengine/pkg/types"
)

func webAsset(t string) platform.Asset {
	return platform.Asset{ID: "a1", TenantID: "t1", Type: t, Target: "https://app.example.com"}
}

// THE handoff property (ADR 0024 gap 3): the AI Pentester proves an SQLi by exploiting it, and before
// this the proposal it produced was a ticket titled "review <finding>" carrying only the finding's own
// description. The strongest evidence in the product met the weakest response.
func TestPropose_ProvenWebFindingGetsAClassCorrectFixNotAReviewTicket(t *testing.T) {
	f := types.Finding{
		ID: "f1", Tool: "sqlmap", RuleID: "sqlmap::boolean-blind", Severity: types.SeverityHigh,
		Title: "SQL injection in search parameter", CWE: []string{"CWE-89"},
		Endpoint:           "https://app.example.com/search?q=",
		VerificationStatus: types.VerificationVerified,
	}
	act, ok := Propose(f, webAsset("web_application"), ids())
	if !ok {
		t.Fatal("a proven web finding must produce an action")
	}
	if strings.HasPrefix(act.Title, "tsengine: review ") {
		t.Fatalf("an exploitation-proven finding must not fall to the generic review ticket: %s", act.Title)
	}
	if act.Payload["remediation_type"] != rtypeParameterizeQuery {
		t.Errorf("want %s, got %v", rtypeParameterizeQuery, act.Payload["remediation_type"])
	}
	rb, _ := act.Payload["remediation"].(string)
	if !strings.Contains(rb, "PARAMETERISED") {
		t.Errorf("the runbook must name the actual fix, got: %s", rb)
	}
	// Grounded (§10): the finding's own endpoint, not the asset-wide target.
	if act.Payload["target"] != "https://app.example.com/search?q=" {
		t.Errorf("target must be the finding's own endpoint, got %v", act.Payload["target"])
	}
}

// A container CVE has a MECHANICAL fix and the scanner already reports the version. Citing it is the
// difference between a fix and a chore.
func TestPropose_ContainerCVECitesTheScannerReportedFixedVersion(t *testing.T) {
	f := types.Finding{
		ID: "f2", Tool: "grype", RuleID: "grype::CVE-2024-1234", Severity: types.SeverityHigh,
		Title:    "CVE-2024-1234 in libfoo",
		ToolArgs: map[string]string{"pkg": "libfoo", "installed_version": "1.2.3", "fixed_version": "1.2.9"},
	}
	act, _ := Propose(f, webAsset("container_image"), ids())
	if act.Payload["remediation_type"] != rtypePackageUpgrade {
		t.Fatalf("want %s, got %v", rtypePackageUpgrade, act.Payload["remediation_type"])
	}
	rb, _ := act.Payload["remediation"].(string)
	for _, want := range []string{"libfoo", "1.2.9", "1.2.3"} {
		if !strings.Contains(rb, want) {
			t.Errorf("runbook must cite the real coordinate %q, got: %s", want, rb)
		}
	}
}

// The refusal that makes the citation trustworthy: with no fixed version reported, the runbook must
// SAY so. An upgrade target we invented is worse than none, because it is actionable and wrong.
func TestPropose_ContainerCVEWithNoFixedVersionNeverInventsOne(t *testing.T) {
	f := types.Finding{
		ID: "f3", Tool: "trivy", RuleID: "trivy::CVE-2024-9999", Severity: types.SeverityHigh,
		Title:    "CVE-2024-9999 in openssl (debian base layer)",
		ToolArgs: map[string]string{"pkg": "openssl", "installed_version": "3.0.11"},
	}
	act, _ := Propose(f, webAsset("container_image"), ids())
	if act.Payload["remediation_type"] != rtypeBaseImageUpgrade {
		t.Fatalf("want %s, got %v", rtypeBaseImageUpgrade, act.Payload["remediation_type"])
	}
	rb, _ := act.Payload["remediation"].(string)
	if !strings.Contains(rb, "did not report a fixed version") {
		t.Errorf("must state that no fixed version was reported, got: %s", rb)
	}
	if strings.Contains(rb, "or later") {
		t.Errorf("must not render an upgrade target it does not have, got: %s", rb)
	}
}

// An unmatched finding must keep the generic ticket. A catalog that guesses is worse than one that
// declines: a confident wrong fix costs more than an honest "review this".
func TestPropose_UnmatchedAppsecFindingKeepsTheGenericTicket(t *testing.T) {
	f := types.Finding{ID: "f4", Tool: "nuclei", RuleID: "nuclei::some-novel-thing",
		Title: "An unclassified observation", Severity: types.SeverityLow}
	act, ok := Propose(f, webAsset("api"), ids())
	if !ok {
		t.Fatal("must still produce an action")
	}
	if _, has := act.Payload["remediation_type"]; has {
		t.Errorf("an unmatched finding must not be labelled with a class: %v", act.Payload)
	}
	if !strings.HasPrefix(act.Title, "tsengine: review ") {
		t.Errorf("want the generic review ticket, got %s", act.Title)
	}
}

// The generic ticket used to end "Remediation generated by tsengine" while containing no remediation —
// a ticket asserting a fix it does not carry.
func TestFixBody_DoesNotClaimARemediationItDoesNotContain(t *testing.T) {
	body := fixBody(types.Finding{ID: "f5", Title: "x", Severity: types.SeverityLow, Tool: "nuclei"})
	if strings.Contains(body, "Remediation generated") {
		t.Fatalf("the generic body must not claim a generated remediation, got: %s", body)
	}
}

// CLASS-LEVEL: every catalog entry must be REACHABLE. A matcher no finding can trip is dead code that
// reads as coverage — the same vacuous-pass shape §14.2 rule 6 forbids in a guard. This table also
// pins the most-specific-first ordering: if a broad class starts shadowing a narrow one, the narrow
// one's row fails here rather than silently degrading a customer's fix.
func TestAppsecCatalog_EveryClassIsReachableAndNamedUniquely(t *testing.T) {
	cases := []struct {
		want string
		f    types.Finding
	}{
		{rtypePackageUpgrade, types.Finding{Tool: "grype", Title: "CVE-2024-1 in libx", ToolArgs: map[string]string{"pkg": "libx", "fixed_version": "2.0"}}},
		{rtypeBaseImageUpgrade, types.Finding{Tool: "trivy", Title: "CVE-2024-2 in alpine base image layer"}},
		{rtypeContainerHardening, types.Finding{Tool: "dockle", Title: "CIS-DI-0001: image runs as root user"}},
		{rtypeImageSigning, types.Finding{Tool: "cosign", Title: "unsigned image digest in registry"}},
		{rtypeParameterizeQuery, types.Finding{Title: "SQL injection", CWE: []string{"CWE-89"}}},
		{rtypeEncodeOutput, types.Finding{Title: "reflected cross-site scripting", CWE: []string{"CWE-79"}}},
		{rtypeSSRFAllowlist, types.Finding{Title: "server-side request forgery", CWE: []string{"CWE-918"}}},
		{rtypeRedirectAllowlist, types.Finding{Title: "open redirect", CWE: []string{"CWE-601"}}},
		{rtypePathCanonicalize, types.Finding{Title: "path traversal", CWE: []string{"CWE-22"}}},
		{rtypeAvoidShellExec, types.Finding{Title: "command injection", CWE: []string{"CWE-78"}}},
		{rtypeEnforceObjectAuthz, types.Finding{Title: "BOLA on /orders/{id}", CWE: []string{"CWE-639"}}},
		{rtypeRotateDefaultCreds, types.Finding{Title: "default login admin:admin", CWE: []string{"CWE-798"}}},
		{rtypeRemoveExposedFile, types.Finding{Title: "exposed .env file", CWE: []string{"CWE-200"}}},
		{rtypeGraphQLIntrospect, types.Finding{Tool: "inql", Title: "GraphQL introspection enabled"}},
		{rtypeTLSHardening, types.Finding{Title: "weak cipher / TLS 1.0 supported", CWE: []string{"CWE-327"}}},
		{rtypeSecurityHeaders, types.Finding{Title: "missing Content-Security-Policy", CWE: []string{"CWE-693"}}},
	}
	reached := map[string]bool{}
	for _, c := range cases {
		got, rb, ok := appsecFixCatalog(c.f)
		if !ok || got != c.want {
			t.Errorf("finding %q: want class %s, got %s (matched=%v)", c.f.Title, c.want, got, ok)
			continue
		}
		if strings.TrimSpace(rb) == "" {
			t.Errorf("class %s produced an empty runbook", got)
		}
		reached[got] = true
	}
	// Every class declared in the catalog must appear above — a class with no representative case is
	// one nobody has shown can fire.
	for _, m := range appsecCatalog {
		if !reached[m.rtype] {
			t.Errorf("catalog class %s is unreachable by any representative finding (dead coverage)", m.rtype)
		}
	}
	seen := map[string]bool{}
	for _, m := range appsecCatalog {
		if seen[m.rtype] {
			t.Errorf("duplicate remediation_type %s: two classes cannot share a machine-readable name", m.rtype)
		}
		seen[m.rtype] = true
	}
	if len(appsecRunbookRemediations) != len(appsecCatalog) {
		t.Errorf("the runbook-routing set must derive from the catalog: %d vs %d", len(appsecRunbookRemediations), len(appsecCatalog))
	}
}

// The three surfaces that had no fix path must now all reach the catalog.
func TestPropose_AllThreeAppsecSurfacesReachTheCatalog(t *testing.T) {
	f := types.Finding{ID: "f6", Title: "reflected cross-site scripting", CWE: []string{"CWE-79"}, Endpoint: "https://x/y"}
	for _, at := range []string{"web_application", "api", "container_image"} {
		act, ok := Propose(f, webAsset(at), ids())
		if !ok || act.Payload["remediation_type"] != rtypeEncodeOutput {
			t.Errorf("%s: want %s, got %v (ok=%v)", at, rtypeEncodeOutput, act.Payload["remediation_type"], ok)
		}
	}
}
