package remediate

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/ClatTribe/tsengine/pkg/platform"
	"github.com/ClatTribe/tsengine/pkg/types"
)

// bulk.go is the "Bulk Fix" capability (Aikido parity: "create ready-to-merge PRs
// that address multiple related alerts at once"). It groups findings by their
// *remediation unit* — the single change that fixes them all — and proposes one
// Action per group instead of one per finding.
//
// Grounding holds (§10): a bulk Action still cites a representative FindingID AND the
// full FindingIDs set it resolves; the grouping key is derived from real tool output
// (a package coordinate / rule id), never guessed.

// fixKey returns the remediation unit a finding belongs to. Findings sharing a key are
// fixable by one change:
//   - SCA findings → the package coordinate (pkg@installed_version from the tool args):
//     every CVE in lodash@4.17.0 is fixed by one upgrade.
//   - everything else → the rule id: the same rule across files is one fix pattern.
func fixKey(f types.Finding) string {
	if pkg := f.ToolArgs["pkg"]; pkg != "" {
		return "pkg:" + pkg + "@" + f.ToolArgs["installed_version"]
	}
	return "rule:" + f.RuleID
}

// FixGroup is a set of findings fixable by one remediation, in stable order.
type FixGroup struct {
	Key      string
	Findings []types.Finding
}

// GroupFindings buckets findings into fix groups, preserving first-seen order (both of
// the groups and of findings within a group) so the output is deterministic.
func GroupFindings(findings []types.Finding) []FixGroup {
	order := []string{}
	idx := map[string]int{}
	var groups []FixGroup
	for _, f := range findings {
		k := fixKey(f)
		i, ok := idx[k]
		if !ok {
			idx[k] = len(groups)
			order = append(order, k)
			groups = append(groups, FixGroup{Key: k})
			i = idx[k]
		}
		groups[i].Findings = append(groups[i].Findings, f)
	}
	_ = order
	return groups
}

// ProposeBulk proposes the MINIMAL set of remediation Actions for a set of findings:
// one Action per fix group. A repository group of ≥2 findings becomes a single bulk
// PR that cites every finding it fixes; singleton groups (and non-repository assets,
// which have no multi-finding PR shape yet) fall back to the per-finding Propose.
// Deterministic + grounded.
func ProposeBulk(findings []types.Finding, asset platform.Asset, idgen func() string) []platform.Action {
	var out []platform.Action
	for _, g := range GroupFindings(findings) {
		if asset.Type == "repository" && len(g.Findings) >= 2 {
			out = append(out, bulkPR(g, asset, idgen))
			continue
		}
		for _, f := range g.Findings {
			if a, ok := Propose(f, asset, idgen); ok {
				out = append(out, a)
			}
		}
	}
	return out
}

// bulkPR builds one ActOpenPR that fixes every finding in the group. Tier 1 (a PR is
// reviewable before merge), same as a single-finding fix.
func bulkPR(g FixGroup, asset platform.Asset, idgen func() string) platform.Action {
	full := asset.Meta["full_name"]
	if full == "" {
		full = asset.Target
	}
	ids := make([]string, 0, len(g.Findings))
	for _, f := range g.Findings {
		ids = append(ids, f.ID)
	}
	rep := g.Findings[0]
	return platform.Action{
		ID: id("act", idgen), TenantID: asset.TenantID, FindingID: rep.ID, FindingIDs: ids,
		ConnectionID: asset.ConnectionID, Kind: platform.ActOpenPR, Tier: tierOpenPR,
		Status: platform.ActProposed, Title: bulkTitle(g),
		Payload: map[string]any{
			"full_name": full,
			"path":      nz(asset.Meta["path"], full),
			"base":      "main",
			"head":      "tsengine/bulk-fix-" + rep.ID,
			"body":      bulkBody(g),
			"bulk":      len(ids),
		},
	}
}

// bulkTitle names the fix. For a package group it names the upgrade; otherwise the
// rule + count.
func bulkTitle(g FixGroup) string {
	n := len(g.Findings)
	if pkg, ok := pkgOf(g); ok {
		if fixed := bestFixedVersion(g); fixed != "" {
			return fmt.Sprintf("tsengine: upgrade %s → %s (fixes %d issues)", pkg, fixed, n)
		}
		return fmt.Sprintf("tsengine: update %s (fixes %d issues)", pkg, n)
	}
	return fmt.Sprintf("tsengine: fix %d findings (%s)", n, g.Findings[0].RuleID)
}

// bulkBody is the PR body — the representative remediation plus the list of every
// finding the PR resolves (so a reviewer sees exactly what is covered).
func bulkBody(g FixGroup) string {
	var b strings.Builder
	if pkg, ok := pkgOf(g); ok {
		fmt.Fprintf(&b, "Bulk dependency fix for **%s**", pkg)
		if fixed := bestFixedVersion(g); fixed != "" {
			fmt.Fprintf(&b, " → upgrade to **%s**", fixed)
		}
		b.WriteString(".\n\n")
	} else {
		fmt.Fprintf(&b, "Bulk fix for rule **%s**.\n\n", g.Findings[0].RuleID)
	}
	fmt.Fprintf(&b, "Resolves %d findings:\n", len(g.Findings))
	for _, f := range g.Findings {
		fmt.Fprintf(&b, "- %s — %s (%s)\n", f.ID, nz(f.Title, f.RuleID), f.Severity)
	}
	b.WriteString("\nRemediation generated by tsengine; review before merge.")
	return b.String()
}

// pkgOf returns the package coordinate if this is an SCA (package-keyed) group.
func pkgOf(g FixGroup) (string, bool) {
	if strings.HasPrefix(g.Key, "pkg:") {
		return strings.TrimPrefix(g.Key, "pkg:"), true
	}
	return "", false
}

// bestFixedVersion returns the highest fixed_version across the group's findings — the
// single upgrade target that clears the whole group (a finding fixed at 4.17.19 is also
// fixed by 4.17.21). Compared by numeric version segments (dependency-free); the
// reviewer confirms before merge.
func bestFixedVersion(g FixGroup) string {
	best := ""
	for _, f := range g.Findings {
		v := f.ToolArgs["fixed_version"]
		if v == "" {
			continue
		}
		if best == "" || versionLess(best, v) {
			best = v
		}
	}
	return best
}

// versionLess reports whether a < b by comparing dot-separated segments numerically
// (the leading integer of each segment; non-numeric suffixes are ignored). Handles the
// common semver case correctly (4.17.21 > 4.17.19, which a lexical compare gets wrong).
func versionLess(a, b string) bool {
	as, bs := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(as) || i < len(bs); i++ {
		var x, y int
		if i < len(as) {
			x = leadingInt(as[i])
		}
		if i < len(bs) {
			y = leadingInt(bs[i])
		}
		if x != y {
			return x < y
		}
	}
	return false
}

// leadingInt parses the leading integer of a version segment (e.g. "21" from "21-rc1");
// 0 if none.
func leadingInt(s string) int {
	end := 0
	for end < len(s) && s[end] >= '0' && s[end] <= '9' {
		end++
	}
	if end == 0 {
		return 0
	}
	n, _ := strconv.Atoi(s[:end])
	return n
}
