// Package remediate turns a grounded finding into a deliverable fix
// (docs/autonomous-team.md §3.5): Propose generates an Action (open a PR, file a
// ticket, apply a config), and Deliverer applies an approved Action through the
// connector's write path. It generalizes the cloud remediation pattern
// (internal/cloudengine) to the dev/web surface.
//
// Delivery is the only write path and is reached ONLY after the HITL gate
// (internal/hitl): the desk decides, then calls Deliverer.Apply.
package remediate

import (
	"context"
	"fmt"

	"github.com/ClatTribe/tsengine/internal/connector"
	"github.com/ClatTribe/tsengine/internal/runner"
	"github.com/ClatTribe/tsengine/internal/store"
	"github.com/ClatTribe/tsengine/pkg/platform"
	"github.com/ClatTribe/tsengine/pkg/types"
)

// Tier policy: a code-fix PR is reversible (review before merge) → tier 1; a direct
// config mutation on live infra is consequential → tier 2 (human-gated). Tier ≥
// platform.GateTier queues at the desk.
const (
	tierOpenPR      = 1
	tierApplyConfig = 2
)

// Propose maps a finding to a remediation Action. It is deterministic and
// evidence-anchored: the Action always cites the finding it fixes (FindingID) and
// carries the remediation text — never a free-form change with no provenance.
func Propose(f types.Finding, asset platform.Asset, idgen func() string) (platform.Action, bool) {
	switch asset.Type {
	case "repository":
		full := asset.Meta["full_name"]
		if full == "" {
			full = asset.Target
		}
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID, ConnectionID: asset.ConnectionID,
			Kind: platform.ActOpenPR, Tier: tierOpenPR, Status: platform.ActProposed,
			Title: "tsengine: fix " + f.Title,
			Payload: map[string]any{
				// both SCM shapes; each connector reads what it needs (github: full_name; gitlab: path)
				"full_name": full,
				"path":      nz(asset.Meta["path"], full),
				"base":      "main",
				"head":      "tsengine/fix-" + f.ID,
				"body":      fixBody(f),
			},
		}, true
	case "cloud_account":
		// Account-scoped runbook by default; when the finding has a live, reversible
		// connector write path (today: AWS S3 public-access block), carry the
		// machine-readable remediation_type + the resource-level target so connector.Apply
		// can promote it from a runbook to a real, HITL-gated mutation (ADR 0009 Phase 5).
		payload := map[string]any{"target": asset.Target, "remediation": fixBody(f)}
		if rt, tgt := liveCloudMutation(f, asset.Meta["provider"]); rt != "" {
			payload["remediation_type"] = rt
			payload["target"] = tgt // the specific bucket, not the whole account
		} else if isIAMPrivescFinding(f) {
			// Layer-correct but not yet live-writable: name the IAM-tighten fix + the principal, so the
			// action is the RIGHT cut (not a generic account runbook). Promotes to a live mutation the
			// moment an IAM-write connector path lands — same pattern as identity's oauth_revoke.
			payload["remediation_type"] = rtypeIAMRestrict
			payload["target"] = nz(f.Endpoint, asset.Target)
		}
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID, ConnectionID: asset.ConnectionID,
			Kind: platform.ActApplyConfig, Tier: tierApplyConfig, Status: platform.ActProposed,
			Title:   "tsengine: remediate " + f.Title,
			Payload: payload,
		}, true
	case "workspace":
		// identity/email posture: a specific runbook ticket per operate rule. Unknown
		// rules fall through to the generic ticket below.
		if a, ok := proposeIdentity(f, asset, idgen); ok {
			return a, true
		}
		fallthrough
	default:
		// no automated fix path yet → file a ticket for the human (reversible, tier 1)
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID, ConnectionID: asset.ConnectionID,
			Kind: platform.ActFileTicket, Tier: 1, Status: platform.ActProposed,
			Title:   "tsengine: review " + f.Title,
			Payload: map[string]any{"summary": fixBody(f)},
		}, true
	}
}

func fixBody(f types.Finding) string {
	return fmt.Sprintf("Finding %s (%s, %s): %s\n\nRemediation generated by tsengine; review before merge.",
		f.ID, f.Severity, f.Tool, nz(f.Description, f.Title))
}

// Filer delivers a file_ticket action to an issue tracker (satisfied by
// *connector.Jira). Optional — when unset, file_ticket actions are a recorded no-op.
type Filer interface {
	FileTicket(ctx context.Context, a platform.Action) error
}

// Deliverer applies an approved Action through the connector write path. It resolves
// the tenant's connection for the action kind, fetches the token, and calls
// connector.Apply. Implements hitl.Applier.
type Deliverer struct {
	Store      store.Store
	Connectors *connector.Registry
	Tokens     runner.Tokens
	Ticket     Filer // optional: files file_ticket actions (e.g. Jira)
}

// Apply executes the action. It routes to the action's own Connection when set
// (so a GitHub finding's fix opens a GitHub PR and a GitLab finding's opens a GitLab
// MR), else falls back to any active connection of the kind the action implies.
// File-ticket actions are a recorded no-op delivery for the MVP.
func (d *Deliverer) Apply(ctx context.Context, a platform.Action) error {
	// File-ticket and a SIGNED incident-disclosure draft both deliver to the issue tracker
	// (the draft, now human-signed, is filed for the human to actually send — the agent
	// never sends regulatory/customer comms itself). No tracker → recorded no-op.
	if a.Kind == platform.ActFileTicket || a.Kind == platform.ActDraftNotification {
		if d.Ticket == nil {
			return nil // no issue tracker configured → recorded no-op (graceful)
		}
		return d.Ticket.FileTicket(ctx, a)
	}
	if !deliverable(a.Kind) {
		return nil // anything else without a write path: recorded, no external write
	}
	conns, err := d.Store.ListConnections(ctx, a.TenantID)
	if err != nil {
		return err
	}
	for _, c := range conns {
		if c.Status != platform.ConnActive {
			continue
		}
		// prefer the action's own connection; else any connection that handles the kind
		if a.ConnectionID != "" {
			if c.ID != a.ConnectionID {
				continue
			}
		} else if !handles(c.Kind, a.Kind) {
			continue
		}
		conn, gerr := d.Connectors.Get(c.Kind)
		if gerr != nil {
			return gerr
		}
		// Re-bind a live cloud-STORAGE mutation to the finding it cites, right before the write — a
		// global-namespace bucket name + a broadly-scoped write credential must not let a tampered/
		// misattributed action hit a resource outside the tenant's scanned account.
		if err := d.verifyCloudTargetGrounded(ctx, a); err != nil {
			return err
		}
		tok, terr := d.Tokens.Resolve(ctx, c)
		if terr != nil {
			return fmt.Errorf("remediate: resolve token: %w", terr)
		}
		return conn.Apply(ctx, c, tok, a)
	}
	return fmt.Errorf("remediate: no active connection to deliver action %s", a.ID)
}

// verifyCloudTargetGrounded re-grounds a live cloud-storage mutation's target to the finding it cites.
// liveCloudMutation sets target == the finding's endpoint, so for those remediation_types the target
// MUST still equal the cited finding's endpoint at apply time. A mismatch means the action was
// retargeted/misattributed after propose (e.g. pointed at a bucket outside the tenant's scanned
// account) — refuse. Grounded like §10: refuse ONLY on a DEFINITIVE mismatch (the finding is present and
// its endpoint differs). If the finding has aged out of the store, proceed — don't false-refuse a legit,
// previously-grounded action that was queued then approved later. Non-cloud-storage actions are untouched.
func (d *Deliverer) verifyCloudTargetGrounded(ctx context.Context, a platform.Action) error {
	rtype, _ := a.Payload["remediation_type"].(string)
	if !cloudStorageRemediations[rtype] {
		return nil // not a global-namespace cloud-storage mutation — this binding doesn't apply
	}
	target, _ := a.Payload["target"].(string)
	if target == "" || a.FindingID == "" {
		return fmt.Errorf("remediate: refusing cloud mutation %s — missing target/finding binding", a.ID)
	}
	findings, err := d.Store.ListFindings(ctx, a.TenantID, store.FindingFilter{})
	if err != nil {
		return err
	}
	for _, f := range findings {
		if f.ID == a.FindingID {
			if f.Endpoint != target {
				return fmt.Errorf("remediate: refusing cloud mutation %s — target %q does not match its finding's resource %q (misattributed or tampered)", a.ID, target, f.Endpoint)
			}
			return nil // matches the cited finding — grounded, proceed
		}
	}
	return nil // the cited finding aged out of the store — proceed (don't false-refuse a previously-grounded action)
}

// deliverable reports whether an action kind writes through a connector at all.
func deliverable(actionKind string) bool {
	return actionKind == platform.ActOpenPR || actionKind == platform.ActApplyConfig
}

// handles reports whether a connector kind can deliver an action kind (the fallback
// when an action carries no explicit ConnectionID).
func handles(connKind, actionKind string) bool {
	switch actionKind {
	case platform.ActOpenPR:
		return connKind == platform.ConnGitHub || connKind == platform.ConnGitLab
	case platform.ActApplyConfig:
		return connKind == platform.ConnAWS || connKind == platform.ConnGCP
	default:
		return false
	}
}

func id(prefix string, idgen func() string) string {
	if idgen != nil {
		return prefix + "-" + idgen()
	}
	return prefix
}

func nz(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
