// Package remediate turns a grounded finding into a deliverable fix
// (docs/autonomous-team.md §3.5): Propose generates an Action (open a PR, file a
// ticket, apply a config), and Deliverer applies an approved Action through the
// connector's write path. It generalizes the cloud remediation pattern
// (internal/cloudengine) to the dev/web surface.
//
// Delivery is the only write path and is reached ONLY after the HITL gate
// (internal/hitl): the desk decides, then calls Deliverer.Apply.
package remediate

import (
	"context"
	"fmt"

	"github.com/ClatTribe/tsengine/internal/connector"
	"github.com/ClatTribe/tsengine/internal/runner"
	"github.com/ClatTribe/tsengine/internal/store"
	"github.com/ClatTribe/tsengine/pkg/platform"
	"github.com/ClatTribe/tsengine/pkg/types"
)

// Tier policy: a code-fix PR is reversible (review before merge) → tier 1; a direct
// config mutation on live infra is consequential → tier 2 (human-gated). Tier ≥
// platform.GateTier queues at the desk.
const (
	tierOpenPR      = 1
	tierApplyConfig = 2
)

// Propose maps a finding to a remediation Action. It is deterministic and
// evidence-anchored: the Action always cites the finding it fixes (FindingID) and
// carries the remediation text — never a free-form change with no provenance.
func Propose(f types.Finding, asset platform.Asset, idgen func() string) (platform.Action, bool) {
	switch asset.Type {
	case "repository":
		full := asset.Meta["full_name"]
		if full == "" {
			full = asset.Target
		}
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID,
			Kind: platform.ActOpenPR, Tier: tierOpenPR, Status: platform.ActProposed,
			Title: "tsengine: fix " + f.Title,
			Payload: map[string]any{
				"full_name": full,
				"base":      "main",
				"head":      "tsengine/fix-" + f.ID,
				"body":      fixBody(f),
			},
		}, true
	case "cloud_account":
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID,
			Kind: platform.ActApplyConfig, Tier: tierApplyConfig, Status: platform.ActProposed,
			Title:   "tsengine: remediate " + f.Title,
			Payload: map[string]any{"target": asset.Target, "remediation": fixBody(f)},
		}, true
	default:
		// no automated fix path yet → file a ticket for the human (reversible, tier 1)
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID,
			Kind: platform.ActFileTicket, Tier: 1, Status: platform.ActProposed,
			Title:   "tsengine: review " + f.Title,
			Payload: map[string]any{"summary": fixBody(f)},
		}, true
	}
}

func fixBody(f types.Finding) string {
	return fmt.Sprintf("Finding %s (%s, %s): %s\n\nRemediation generated by tsengine; review before merge.",
		f.ID, f.Severity, f.Tool, nz(f.Description, f.Title))
}

// Deliverer applies an approved Action through the connector write path. It resolves
// the tenant's connection for the action kind, fetches the token, and calls
// connector.Apply. Implements hitl.Applier.
type Deliverer struct {
	Store      store.Store
	Connectors *connector.Registry
	Tokens     runner.Tokens
}

// Apply executes the action. File-ticket actions are a no-op delivery for the MVP
// (the platform records them; an integration ships them later).
func (d *Deliverer) Apply(ctx context.Context, a platform.Action) error {
	kind, ok := connKindFor(a.Kind)
	if !ok {
		return nil // ActFileTicket and friends: recorded, no external write yet
	}
	conns, err := d.Store.ListConnections(ctx, a.TenantID)
	if err != nil {
		return err
	}
	for _, c := range conns {
		if c.Kind != kind || c.Status != platform.ConnActive {
			continue
		}
		conn, err := d.Connectors.Get(c.Kind)
		if err != nil {
			return err
		}
		tok, err := d.Tokens.Resolve(ctx, c)
		if err != nil {
			return fmt.Errorf("remediate: resolve token: %w", err)
		}
		return conn.Apply(ctx, c, tok, a)
	}
	return fmt.Errorf("remediate: no active %s connection to apply action %s", kind, a.ID)
}

// connKindFor maps an action kind to the connector kind that delivers it.
func connKindFor(actionKind string) (string, bool) {
	switch actionKind {
	case platform.ActOpenPR:
		return platform.ConnGitHub, true
	case platform.ActApplyConfig:
		return platform.ConnAWS, true // first cloud target; extend per provider
	default:
		return "", false
	}
}

func id(prefix string, idgen func() string) string {
	if idgen != nil {
		return prefix + "-" + idgen()
	}
	return prefix
}

func nz(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
