// Package remediate turns a grounded finding into a deliverable fix
// (docs/autonomous-team.md §3.5): Propose generates an Action (open a PR, file a
// ticket, apply a config), and Deliverer applies an approved Action through the
// connector's write path. It generalizes the cloud remediation pattern
// (internal/cloudengine) to the dev/web surface.
//
// Delivery is the only write path and is reached ONLY after the HITL gate
// (internal/hitl): the desk decides, then calls Deliverer.Apply.
package remediate

import (
	"context"
	"fmt"

	"github.com/ClatTribe/tsengine/internal/connector"
	"github.com/ClatTribe/tsengine/internal/runner"
	"github.com/ClatTribe/tsengine/internal/store"
	"github.com/ClatTribe/tsengine/pkg/platform"
	"github.com/ClatTribe/tsengine/pkg/types"
)

// Tier policy: a code-fix PR is reversible (review before merge) → tier 1; a direct
// config mutation on live infra is consequential → tier 2 (human-gated). Tier ≥
// platform.GateTier queues at the desk.
const (
	tierOpenPR      = 1
	tierApplyConfig = 2
)

// Propose maps a finding to a remediation Action. It is deterministic and
// evidence-anchored: the Action always cites the finding it fixes (FindingID) and
// carries the remediation text — never a free-form change with no provenance.
func Propose(f types.Finding, asset platform.Asset, idgen func() string) (platform.Action, bool) {
	switch asset.Type {
	case "repository":
		full := asset.Meta["full_name"]
		if full == "" {
			full = asset.Target
		}
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID, ConnectionID: asset.ConnectionID,
			Kind: platform.ActOpenPR, Tier: tierOpenPR, Status: platform.ActProposed,
			Title: "tsengine: fix " + f.Title,
			Payload: map[string]any{
				// both SCM shapes; each connector reads what it needs (github: full_name; gitlab: path)
				"full_name": full,
				"path":      nz(asset.Meta["path"], full),
				"base":      "main",
				"head":      "tsengine/fix-" + f.ID,
				"body":      fixBody(f),
			},
		}, true
	case "cloud_account":
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID, ConnectionID: asset.ConnectionID,
			Kind: platform.ActApplyConfig, Tier: tierApplyConfig, Status: platform.ActProposed,
			Title:   "tsengine: remediate " + f.Title,
			Payload: map[string]any{"target": asset.Target, "remediation": fixBody(f)},
		}, true
	default:
		// no automated fix path yet → file a ticket for the human (reversible, tier 1)
		return platform.Action{
			ID: id("act", idgen), TenantID: asset.TenantID, FindingID: f.ID, ConnectionID: asset.ConnectionID,
			Kind: platform.ActFileTicket, Tier: 1, Status: platform.ActProposed,
			Title:   "tsengine: review " + f.Title,
			Payload: map[string]any{"summary": fixBody(f)},
		}, true
	}
}

func fixBody(f types.Finding) string {
	return fmt.Sprintf("Finding %s (%s, %s): %s\n\nRemediation generated by tsengine; review before merge.",
		f.ID, f.Severity, f.Tool, nz(f.Description, f.Title))
}

// Deliverer applies an approved Action through the connector write path. It resolves
// the tenant's connection for the action kind, fetches the token, and calls
// connector.Apply. Implements hitl.Applier.
type Deliverer struct {
	Store      store.Store
	Connectors *connector.Registry
	Tokens     runner.Tokens
}

// Apply executes the action. It routes to the action's own Connection when set
// (so a GitHub finding's fix opens a GitHub PR and a GitLab finding's opens a GitLab
// MR), else falls back to any active connection of the kind the action implies.
// File-ticket actions are a recorded no-op delivery for the MVP.
func (d *Deliverer) Apply(ctx context.Context, a platform.Action) error {
	if !deliverable(a.Kind) {
		return nil // ActFileTicket and friends: recorded, no external write yet
	}
	conns, err := d.Store.ListConnections(ctx, a.TenantID)
	if err != nil {
		return err
	}
	for _, c := range conns {
		if c.Status != platform.ConnActive {
			continue
		}
		// prefer the action's own connection; else any connection that handles the kind
		if a.ConnectionID != "" {
			if c.ID != a.ConnectionID {
				continue
			}
		} else if !handles(c.Kind, a.Kind) {
			continue
		}
		conn, gerr := d.Connectors.Get(c.Kind)
		if gerr != nil {
			return gerr
		}
		tok, terr := d.Tokens.Resolve(ctx, c)
		if terr != nil {
			return fmt.Errorf("remediate: resolve token: %w", terr)
		}
		return conn.Apply(ctx, c, tok, a)
	}
	return fmt.Errorf("remediate: no active connection to deliver action %s", a.ID)
}

// deliverable reports whether an action kind writes through a connector at all.
func deliverable(actionKind string) bool {
	return actionKind == platform.ActOpenPR || actionKind == platform.ActApplyConfig
}

// handles reports whether a connector kind can deliver an action kind (the fallback
// when an action carries no explicit ConnectionID).
func handles(connKind, actionKind string) bool {
	switch actionKind {
	case platform.ActOpenPR:
		return connKind == platform.ConnGitHub || connKind == platform.ConnGitLab
	case platform.ActApplyConfig:
		return connKind == platform.ConnAWS || connKind == platform.ConnGCP
	default:
		return false
	}
}

func id(prefix string, idgen func() string) string {
	if idgen != nil {
		return prefix + "-" + idgen()
	}
	return prefix
}

func nz(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
