package report

import (
	"fmt"
	"html"
	"strings"
)

// HTML renders a self-contained, branded HTML report (inline CSS, no external
// assets) — printable to PDF from any browser.
func HTML(r *Report) string {
	var b strings.Builder
	b.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">")
	fmt.Fprintf(&b, "<title>%s</title>", esc(r.Title))
	b.WriteString("<style>" + css + "</style></head><body>")

	// Cover / header
	b.WriteString(`<header class="cover">`)
	fmt.Fprintf(&b, `<div class="kicker">%s</div>`, esc(r.Kind))
	fmt.Fprintf(&b, "<h1>%s</h1>", esc(r.Title))
	b.WriteString(`<div class="meta">`)
	metaRow(&b, "Target", r.Target)
	if r.Org != "" {
		metaRow(&b, "Prepared for", r.Org)
	}
	metaRow(&b, "Generated", r.GeneratedAt.Format("2006-01-02 15:04 MST"))
	if r.Engine != "" {
		metaRow(&b, "Engine", r.Engine)
	}
	if r.Signed {
		metaRow(&b, "Evidence", "cryptographically signed (signer "+r.Signer+")")
	}
	b.WriteString(`</div></header>`)

	// Risk dashboard
	b.WriteString(`<section><h2>Executive summary</h2>`)
	fmt.Fprintf(&b, "<p>%s</p>", esc(r.autoSummary()))
	b.WriteString(`<div class="dash">`)
	c := r.Counts()
	for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
		fmt.Fprintf(&b, `<div class="card sev-%s"><div class="n">%d</div><div class="l">%s</div></div>`, sev, c[sev], strings.Title(sev)) //nolint:staticcheck
	}
	b.WriteString(`</div>`)
	fmt.Fprintf(&b, `<p class="risk">Overall risk rating: <span class="sev-%s pill">%s</span></p>`, strings.ToLower(r.RiskRating()), esc(r.RiskRating()))
	b.WriteString(`</section>`)

	// Findings
	if len(r.Findings) > 0 {
		b.WriteString(`<section><h2>Findings</h2>`)
		for i, f := range r.Findings {
			renderFindingHTML(&b, i+1, f)
		}
		b.WriteString(`</section>`)
	}

	// Methodology
	if len(r.Methodology) > 0 {
		b.WriteString(`<section><h2>Methodology</h2><ul>`)
		for _, m := range r.Methodology {
			fmt.Fprintf(&b, "<li>%s</li>", esc(m))
		}
		b.WriteString(`</ul></section>`)
	}
	if len(r.Meta) > 0 {
		b.WriteString(`<section><h2>Appendix — engagement metadata</h2><table class="kv">`)
		for _, k := range sortedKeys(r.Meta) {
			if r.Meta[k] != "" {
				fmt.Fprintf(&b, "<tr><th>%s</th><td><code>%s</code></td></tr>", esc(k), esc(r.Meta[k]))
			}
		}
		b.WriteString(`</table></section>`)
	}

	b.WriteString(`<footer>Generated by tsengine — findings are evidence-grounded: each is backed by a reproducible indicator, not an unverified claim.</footer>`)
	b.WriteString("</body></html>")
	return b.String()
}

func renderFindingHTML(b *strings.Builder, n int, f Finding) {
	sev := strings.ToLower(f.Severity)
	fmt.Fprintf(b, `<article class="finding"><div class="fhead"><span class="pill sev-%s">%s</span><h3>%d. %s</h3>`, sev, strings.Title(sev), n, esc(f.Title)) //nolint:staticcheck
	if f.Status == "verified" {
		b.WriteString(`<span class="verified">✓ verified</span>`)
	}
	b.WriteString(`</div>`)
	if f.Endpoint != "" {
		fmt.Fprintf(b, `<p class="loc"><code>%s</code></p>`, esc(f.Endpoint))
	}
	if f.Description != "" {
		fmt.Fprintf(b, "<p>%s</p>", esc(f.Description))
	}
	if f.ThreatIntel != "" {
		fmt.Fprintf(b, `<p class="ti"><strong>Threat intel:</strong> %s</p>`, esc(f.ThreatIntel))
	}
	if len(f.CWE) > 0 {
		fmt.Fprintf(b, `<p><strong>CWE:</strong> %s</p>`, esc(strings.Join(f.CWE, ", ")))
	}
	if len(f.Evidence) > 0 {
		b.WriteString(`<div class="evidence"><strong>Evidence</strong><pre>`)
		for _, e := range f.Evidence {
			b.WriteString(esc(e))
			b.WriteString("\n")
		}
		b.WriteString(`</pre></div>`)
	}
	if f.Remediation != "" {
		fmt.Fprintf(b, `<p class="remed"><strong>Remediation:</strong> %s</p>`, esc(f.Remediation))
	}
	if len(f.Compliance) > 0 {
		b.WriteString(`<p class="compl"><strong>Affected controls:</strong> `)
		var parts []string
		for _, fw := range sortedKeys2(f.Compliance) {
			parts = append(parts, fmt.Sprintf("%s (%s)", esc(fw), esc(strings.Join(f.Compliance[fw], ", "))))
		}
		b.WriteString(strings.Join(parts, "; "))
		b.WriteString(`</p>`)
	}
	b.WriteString(`</article>`)
}

func metaRow(b *strings.Builder, k, v string) {
	fmt.Fprintf(b, `<div><span class="k">%s</span><span class="v">%s</span></div>`, esc(k), esc(v))
}

func esc(s string) string { return html.EscapeString(s) }

const css = `
:root{--c:#dc2626;--h:#ea580c;--m:#d97706;--l:#2563eb;--i:#6b7280;--ink:#111827;--mut:#6b7280;--line:#e5e7eb}
*{box-sizing:border-box}body{font:15px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--ink);margin:0;padding:0 24px 64px}
.cover{padding:48px 0 24px;border-bottom:3px solid var(--ink);margin-bottom:24px}
.kicker{text-transform:uppercase;letter-spacing:.12em;font-size:12px;color:var(--mut);font-weight:600}
h1{font-size:30px;margin:.2em 0 .6em}h2{font-size:20px;border-bottom:1px solid var(--line);padding-bottom:6px;margin-top:36px}
h3{font-size:17px;margin:0}
.meta{display:flex;flex-wrap:wrap;gap:6px 28px;color:var(--mut);font-size:14px}
.meta .k{display:inline-block;min-width:96px;color:var(--mut)}.meta .v{color:var(--ink)}
.dash{display:flex;gap:12px;margin:18px 0}
.card{flex:1;border:1px solid var(--line);border-radius:10px;padding:14px;text-align:center}
.card .n{font-size:28px;font-weight:700}.card .l{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:var(--mut)}
.pill{display:inline-block;padding:2px 10px;border-radius:999px;color:#fff;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.04em}
.sev-critical{--x:var(--c)}.sev-high{--x:var(--h)}.sev-medium{--x:var(--m)}.sev-low{--x:var(--l)}.sev-info{--x:var(--i)}.sev-none{--x:var(--i)}
.pill{background:var(--x)}.card.sev-critical .n{color:var(--c)}.card.sev-high .n{color:var(--h)}.card.sev-medium .n{color:var(--m)}.card.sev-low .n{color:var(--l)}.card.sev-info .n{color:var(--i)}
.risk{font-size:16px;font-weight:600}
.finding{border:1px solid var(--line);border-left:5px solid var(--x,#999);border-radius:10px;padding:16px 18px;margin:16px 0}
.fhead{display:flex;align-items:center;gap:12px;flex-wrap:wrap}
.verified{margin-left:auto;color:#059669;font-weight:700;font-size:13px}
.loc code,code{background:#f3f4f6;padding:2px 6px;border-radius:6px;font-size:13px}
.evidence pre{background:#0f172a;color:#e2e8f0;padding:12px;border-radius:8px;overflow:auto;font-size:12.5px;white-space:pre-wrap;word-break:break-all}
.remed{background:#ecfdf5;border-radius:8px;padding:10px 12px}
.compl{color:var(--mut);font-size:13px}.ti{color:var(--mut);font-size:14px}
table.kv{border-collapse:collapse}table.kv th{text-align:left;padding:4px 16px 4px 0;color:var(--mut);font-weight:600;vertical-align:top}
footer{margin-top:48px;padding-top:16px;border-top:1px solid var(--line);color:var(--mut);font-size:12px}
@media print{body{padding:0}.finding{break-inside:avoid}}
`
