package report

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the report as a portable Markdown document.
func Markdown(r *Report) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", r.Title)
	if r.Org != "" {
		fmt.Fprintf(&b, "**Prepared for:** %s  \n", r.Org)
	}
	fmt.Fprintf(&b, "**Target:** %s  \n", r.Target)
	fmt.Fprintf(&b, "**Assessment type:** %s  \n", r.Kind)
	fmt.Fprintf(&b, "**Generated:** %s  \n", r.GeneratedAt.Format("2006-01-02 15:04 MST"))
	if r.Engine != "" {
		fmt.Fprintf(&b, "**Engine:** %s  \n", r.Engine)
	}
	if r.Signed {
		fmt.Fprintf(&b, "**Evidence:** cryptographically signed (signer `%s`)  \n", r.Signer)
	}
	b.WriteString("\n---\n\n")

	// Executive summary + risk dashboard
	b.WriteString("## Executive summary\n\n")
	b.WriteString(r.autoSummary())
	b.WriteString("\n\n")
	b.WriteString("| Severity | Count |\n|---|---|\n")
	c := r.Counts()
	for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
		if c[sev] > 0 {
			fmt.Fprintf(&b, "| %s | %d |\n", strings.Title(sev), c[sev]) //nolint:staticcheck
		}
	}
	fmt.Fprintf(&b, "| **Total** | **%d** |\n\n", len(r.Findings))
	fmt.Fprintf(&b, "**Overall risk rating: %s**\n\n", r.RiskRating())

	// Findings table of contents
	if len(r.Findings) > 0 {
		b.WriteString("## Findings\n\n")
		for i, f := range r.Findings {
			fmt.Fprintf(&b, "%d. [%s] **%s** — %s%s\n", i+1, strings.ToUpper(f.Severity), f.Title, f.Endpoint, statusBadge(f.Status))
		}
		b.WriteString("\n")
		for i, f := range r.Findings {
			renderFindingMD(&b, i+1, f)
		}
	}

	// Methodology + appendix
	if len(r.Methodology) > 0 {
		b.WriteString("## Methodology\n\n")
		for _, m := range r.Methodology {
			fmt.Fprintf(&b, "- %s\n", m)
		}
		b.WriteString("\n")
	}
	if len(r.Meta) > 0 {
		b.WriteString("## Appendix — engagement metadata\n\n")
		for _, k := range sortedKeys(r.Meta) {
			if r.Meta[k] != "" {
				fmt.Fprintf(&b, "- **%s:** `%s`\n", k, r.Meta[k])
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n\n_Generated by tsengine. Findings are evidence-grounded: each is backed by a reproducible indicator, not an unverified claim._\n")
	return b.String()
}

func renderFindingMD(b *strings.Builder, n int, f Finding) {
	fmt.Fprintf(b, "### %d. %s\n\n", n, f.Title)
	fmt.Fprintf(b, "**Severity:** %s", strings.Title(f.Severity)) //nolint:staticcheck
	if f.Status != "" {
		fmt.Fprintf(b, " · **Status:** %s", f.Status)
	}
	if f.ID != "" {
		fmt.Fprintf(b, " · **ID:** `%s`", f.ID)
	}
	b.WriteString("\n\n")
	if f.Endpoint != "" {
		fmt.Fprintf(b, "**Location:** `%s`\n\n", f.Endpoint)
	}
	if f.Description != "" {
		fmt.Fprintf(b, "%s\n\n", f.Description)
	}
	if len(f.CWE) > 0 {
		fmt.Fprintf(b, "**CWE:** %s\n\n", strings.Join(f.CWE, ", "))
	}
	if f.ThreatIntel != "" {
		fmt.Fprintf(b, "**Threat intel:** %s\n\n", f.ThreatIntel)
	}
	if len(f.Evidence) > 0 {
		b.WriteString("**Evidence:**\n\n```\n")
		for _, e := range f.Evidence {
			b.WriteString(e)
			b.WriteString("\n")
		}
		b.WriteString("```\n\n")
	}
	if f.Remediation != "" {
		fmt.Fprintf(b, "**Remediation:** %s\n\n", f.Remediation)
	}
	if len(f.Compliance) > 0 {
		b.WriteString("**Affected controls:** ")
		var parts []string
		for _, fw := range sortedKeys2(f.Compliance) {
			parts = append(parts, fmt.Sprintf("%s (%s)", fw, strings.Join(f.Compliance[fw], ", ")))
		}
		b.WriteString(strings.Join(parts, "; "))
		b.WriteString("\n\n")
	}
	b.WriteString("---\n\n")
}

func statusBadge(status string) string {
	if status == "verified" {
		return " ✓ verified"
	}
	return ""
}

func sortedKeys(m map[string]string) []string {
	k := make([]string, 0, len(m))
	for key := range m {
		k = append(k, key)
	}
	sort.Strings(k)
	return k
}

func sortedKeys2(m map[string][]string) []string {
	k := make([]string, 0, len(m))
	for key := range m {
		k = append(k, key)
	}
	sort.Strings(k)
	return k
}
