import { ImageResponse } from "next/og";

// The browser-tab favicon — a branded shield on the accent, matching the OG card's mark.
// Generated by next/og (no static asset to commit); Next emits the <link rel="icon"> for it.
export const size = { width: 32, height: 32 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#6366f1",
          borderRadius: "7px",
        }}
      >
        <svg width="21" height="21" viewBox="0 0 24 24" fill="none">
          {/* white shield */}
          <path d="M12 2l8 3v6c0 5-3.4 8.4-8 11-4.6-2.6-8-6-8-11V5l8-3z" fill="#ffffff" />
          {/* upward tensor node-chevron — matches the brand mark, legible at 16px */}
          <path
            d="M8.2 15L12 9l3.8 6"
            stroke="#6366f1"
            strokeWidth="1.7"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
          <circle cx="8.2" cy="15" r="1.35" fill="#6366f1" />
          <circle cx="15.8" cy="15" r="1.35" fill="#6366f1" />
          <circle cx="12" cy="9" r="1.6" fill="#6366f1" />
        </svg>
      </div>
    ),
    { ...size },
  );
}
