import { ImageResponse } from "next/og";
import { SHIELD, CHIP, MARK, EMERALD, lattice } from "@/lib/brand-mark.mjs";

// The PNG tab icon, generated by next/og from the SAME geometry as the React
// component (lib/brand-mark.mjs). It used to be a hand-simplified second drawing
// of the old mark and had silently drifted out of sync with it; importing the
// geometry is what stops that recurring.
//
// This is NOT the icon Google shows in search results — that one is the static
// app/favicon.ico, because next/og serves this at /icon?<content-hash>, a URL
// that moves whenever the artwork does, and Google needs the favicon to sit at a
// URL that does not change. Both ship; Next emits a <link> for each.
//
// 48px, not 32: Google wants a favicon that is a multiple of 48 and browsers
// downsample cleanly, so one size serves both.
export const size = { width: 48, height: 48 };
export const contentType = "image/png";

// The default cut, which is already tuned for small sizes — see lib/brand-mark.mjs.
const L = lattice();

export default function Icon() {
  const [ax, ay] = L.accent;
  return new ImageResponse(
    (
      <div style={{ width: "100%", height: "100%", display: "flex" }}>
        <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
          <rect width="48" height="48" rx="10" fill={CHIP} />
          {/* the mark bleeds slightly toward the chip edge so it is not a dot in a box */}
          <g transform="translate(24 24) scale(1.04) translate(-24 -24)">
            <path fillRule="evenodd" fill={MARK} d={`${SHIELD} ${L.path}`} />
            <rect x={ax} y={ay} width={L.cell} height={L.cell} rx={L.radius} fill={EMERALD} />
          </g>
        </svg>
      </div>
    ),
    { ...size },
  );
}
