package cloudengine

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/ClatTribe/tsengine/internal/cloudgraph"
	"github.com/ClatTribe/tsengine/pkg/types"
)

// LLM-generated emulated cloud account — an INDEPENDENT-generator benchmark.
//
// The in-distribution synthetic bench (synthgen.go) and the held-out bench
// (holdout.go) are both authored by the same hand that wrote the engine. The
// honest objection is "you're still grading your own homework." This closes that:
// the emulated account AND its answer key are generated by an external model
// (Gemini), which has no knowledge of the engine's internals. We then run the
// account through the REAL pipeline the AI Cloud Security Engineer sits on —
// serialize to the CloudQuery/Cartography inventory JSON, ingest it, and Assess —
// and score the engine's verdict against the generator's independent answer key.
//
// This is the "AI cloud engineer built on top of CloudQuery" path: the model is
// the eyes (it composes the account the way a CloudQuery sync would surface it),
// the deterministic engine is the brain (it reasons over the pinned inventory).
// Neither side can collude — the generator doesn't see FindPaths/the oracle, and
// the engine doesn't see the answer key.

// EmulatedAccount is one externally-generated account + its independent labels.
type EmulatedAccount struct {
	Inventory cloudgraph.Inventory `json:"inventory"`
	Prowler   []types.Finding      `json:"prowler"`
	Key       AnswerKey            `json:"answer_key"`
	Raw       string               `json:"-"` // the model's raw JSON (for --out / debugging)
}

// AnswerKey is the generator's ground truth: which jewels are genuinely reachable
// (must-find) and which config-bad findings are inert (must-downgrade).
type AnswerKey struct {
	RealTargets   []string     `json:"real_targets"`
	InertFindings []InertLabel `json:"inert_findings"`
}

// InertLabel marks one prowler finding the generator says is config-bad but inert.
type InertLabel struct {
	FindingID string `json:"finding_id"`
	Resource  string `json:"resource"`
	Reason    string `json:"reason"`
}

// llmAccount is the wire shape we ask the model to emit (prowler simplified so the
// model can't mis-format the join key — we build types.Finding ourselves).
type llmAccount struct {
	Inventory cloudgraph.Inventory `json:"inventory"`
	Prowler   []struct {
		ID       string `json:"id"`
		Resource string `json:"resource"`
		CheckID  string `json:"check_id"`
		Severity string `json:"severity"`
	} `json:"prowler"`
	AnswerKey AnswerKey `json:"answer_key"`
}

// GenerateEmulated asks the model to compose an independent emulated AWS account
// with nReal genuine internet→jewel paths and nDecoy config-bad-but-inert
// findings, plus an answer key. The result is validated for internal consistency
// before it is returned.
func GenerateEmulated(ctx context.Context, llm LLM, nReal, nDecoy int) (*EmulatedAccount, error) {
	if llm == nil {
		return nil, fmt.Errorf("emulate: no LLM configured (set LLM_API_KEY)")
	}
	out, err := llm.Generate(ctx, buildEmulatePrompt(nReal, nDecoy))
	if err != nil {
		return nil, fmt.Errorf("emulate: model generate: %w", err)
	}
	var la llmAccount
	if err := json.Unmarshal([]byte(stripFences(out)), &la); err != nil {
		return nil, fmt.Errorf("emulate: parse model JSON: %w", err)
	}

	acc := &EmulatedAccount{Inventory: la.Inventory, Key: la.AnswerKey, Raw: out}
	if acc.Inventory.Provider == "" {
		acc.Inventory.Provider = "aws"
	}
	for _, p := range la.Prowler {
		sev := types.Severity(strings.ToLower(p.Severity))
		if sev == "" {
			sev = types.SeverityHigh
		}
		acc.Prowler = append(acc.Prowler, types.Finding{
			ID: p.ID, RuleID: "prowler::" + p.CheckID, Tool: "prowler", Severity: sev,
			Title: p.CheckID,
			// Endpoint "<type> <resource> @region": resourceOf() joins on field[1].
			Endpoint: fmt.Sprintf("resource %s @us-east-1", p.Resource),
		})
	}
	if err := acc.validate(); err != nil {
		return acc, err
	}
	return acc, nil
}

// validate checks the model's answer key references real entities — a malformed
// scenario must not silently score as an engine failure.
func (a *EmulatedAccount) validate() error {
	nodes := map[string]bool{}
	for _, r := range a.Inventory.Resources {
		nodes[r.ID] = true
	}
	findings := map[string]bool{}
	for _, f := range a.Prowler {
		findings[f.ID] = true
	}
	if len(a.Key.RealTargets) == 0 && len(a.Key.InertFindings) == 0 {
		return fmt.Errorf("emulate: answer key is empty")
	}
	for _, t := range a.Key.RealTargets {
		if !nodes[t] {
			return fmt.Errorf("emulate: answer-key real_target %q is not a resource in the inventory", t)
		}
	}
	for _, il := range a.Key.InertFindings {
		if !findings[il.FindingID] {
			return fmt.Errorf("emulate: answer-key inert finding %q is not in the prowler set", il.FindingID)
		}
	}
	return nil
}

// Snapshot ingests the emulated account through the real CloudQuery-inventory
// path: serialize to inventory JSON, then ParseInventory + Ingest — exactly what
// `tsengine cloud-assess` does with a CloudQuery/Cartography export.
func (a *EmulatedAccount) Snapshot() (*cloudgraph.Snapshot, error) {
	b, err := json.Marshal(a.Inventory)
	if err != nil {
		return nil, err
	}
	inv, err := cloudgraph.ParseInventory(b)
	if err != nil {
		return nil, err
	}
	return cloudgraph.Ingest(inv), nil
}

// EmulatedScore compares the engine's assessment against the generator's key.
type EmulatedScore struct {
	RealTotal   int      `json:"real_total"`
	RealFound   int      `json:"real_found"`
	PathRecall  float64  `json:"path_recall"`
	InertTotal  int      `json:"inert_total"`
	InertDown   int      `json:"inert_downgraded"`
	FPReduction float64  `json:"fp_reduction"`
	ExtraPaths  []string `json:"extra_paths,omitempty"` // engine paths whose target isn't in the key
	MissedReal  []string `json:"missed_real,omitempty"` // key real targets the engine didn't reach
	Pass        bool     `json:"pass"`
}

// ScoreEmulated scores the engine output against the independent answer key.
func ScoreEmulated(acc *EmulatedAccount, a *types.AIAssessment) EmulatedScore {
	realTargets := map[string]bool{}
	for _, t := range acc.Key.RealTargets {
		realTargets[t] = true
	}
	downgraded := map[string]bool{}
	for _, d := range a.Downgraded {
		downgraded[d] = true
	}
	foundEnds := map[string]bool{}
	var extra []string
	for _, p := range a.Paths {
		end := pathEnd(p)
		if realTargets[end] {
			foundEnds[end] = true
		} else {
			extra = appendUnique(extra, end)
		}
	}
	var s EmulatedScore
	for t := range realTargets {
		s.RealTotal++
		if foundEnds[t] {
			s.RealFound++
		} else {
			s.MissedReal = appendUnique(s.MissedReal, t)
		}
	}
	for _, il := range acc.Key.InertFindings {
		s.InertTotal++
		if downgraded[il.FindingID] {
			s.InertDown++
		}
	}
	s.PathRecall = ratio(s.RealFound, s.RealTotal)
	s.FPReduction = ratio(s.InertDown, s.InertTotal)
	sort.Strings(extra)
	sort.Strings(s.MissedReal)
	s.ExtraPaths = extra
	s.Pass = s.RealFound == s.RealTotal && s.InertDown == s.InertTotal && len(extra) == 0
	return s
}

// RenderEmulated formats the independent-generator scorecard.
func RenderEmulated(acc *EmulatedAccount, s EmulatedScore) string {
	var b strings.Builder
	verdict := "PASS"
	if !s.Pass {
		verdict = "FAIL / divergence — see below"
	}
	fmt.Fprintf(&b, "=== AI Cloud Engineer vs INDEPENDENTLY-GENERATED account (model: external LLM) ===\n")
	fmt.Fprintf(&b, "account: %s (%d resources, %d prowler findings)\n",
		acc.Inventory.AccountID, len(acc.Inventory.Resources), len(acc.Prowler))
	fmt.Fprintf(&b, "generator answer key: %d real target(s), %d inert finding(s)\n",
		len(acc.Key.RealTargets), len(acc.Key.InertFindings))
	fmt.Fprintf(&b, "attack-path recall:   %.2f%%  (%d/%d real targets reached)\n",
		s.PathRecall*100, s.RealFound, s.RealTotal)
	fmt.Fprintf(&b, "FP-reduction:         %.2f%%  (%d/%d inert findings downgraded)\n",
		s.FPReduction*100, s.InertDown, s.InertTotal)
	fmt.Fprintf(&b, "verdict:              %s\n", verdict)
	if len(s.MissedReal) > 0 {
		fmt.Fprintf(&b, "MISSED real targets (engine under-reported): %s\n", strings.Join(s.MissedReal, ", "))
	}
	if len(s.ExtraPaths) > 0 {
		fmt.Fprintf(&b, "EXTRA paths (engine reported a target not in the key — over-report, OR the\n")
		fmt.Fprintf(&b, "  generator under-labeled): %s\n", strings.Join(s.ExtraPaths, ", "))
	}
	fmt.Fprintf(&b, "note: the account + answer key were authored by an external model with no\n")
	fmt.Fprintf(&b, "  knowledge of the engine internals; the engine never saw the key. This is the\n")
	fmt.Fprintf(&b, "  independent-generator check that the in-distribution bench cannot give.\n")
	return b.String()
}

func buildEmulatePrompt(nReal, nDecoy int) string {
	var b strings.Builder
	b.WriteString("You are a cloud security architect building a REALISTIC but FICTIONAL AWS account ")
	b.WriteString("to test an attack-path analyzer. Output ONLY strict JSON (no prose, no markdown fences).\n\n")
	b.WriteString("The account is a graph of resources and the relationships between them. Use these EXACT shapes.\n")
	b.WriteString("inventory.resources[]: {id, kind, type, name, public(bool), sensitive(\"\"|\"low\"|\"high\"), privileged(bool)}\n")
	b.WriteString("  kind is one of: resource | principal | network | data. Use id \"internet\" (kind network) as the external attacker.\n")
	b.WriteString("inventory.reaches[]:  {from, to, condition}  // network reachability; from may be \"internet\"\n")
	b.WriteString("inventory.runs_as[]:  {compute, principal}    // an EC2/Lambda runs with an IAM role\n")
	b.WriteString("inventory.trusts[]:   {principal, role, condition}   // principal can sts:AssumeRole role\n")
	b.WriteString("inventory.grants[]:   {principal, resource, condition} // principal can read a resource\n")
	b.WriteString("inventory.privescs[]: {principal, target, detail}     // a known IAM privesc move\n")
	b.WriteString("prowler[]: {id, resource, check_id, severity}   // one finding per misconfigured resource; resource = a resource id\n")
	b.WriteString("answer_key.real_targets[]: resource ids of crown jewels (sensitive==\"high\" data OR privileged principal) ")
	b.WriteString("that ARE genuinely reachable from \"internet\" via an UNCONDITIONED chain of the relationships above.\n")
	b.WriteString("answer_key.inert_findings[]: {finding_id, resource, reason} for each prowler finding that is config-bad ")
	b.WriteString("but NOT a real attack path — e.g. the resource holds no sensitive data, has no network path from the internet, ")
	b.WriteString("or the only chain to it crosses an edge gated by a runtime condition (set that edge's \"condition\", e.g. \"aws:MultiFactorAuthPresent=true\").\n\n")
	fmt.Fprintf(&b, "Requirements:\n- Exactly %d genuinely-reachable real path(s) ending at distinct crown jewels (list each jewel id in real_targets).\n", nReal)
	fmt.Fprintf(&b, "- Exactly %d config-bad-but-inert finding(s) (list each in inert_findings with a precise reason).\n", nDecoy)
	b.WriteString("- A real path is UNCONDITIONED end to end (no condition on any edge). An inert decoy must be inert for a concrete reason.\n")
	b.WriteString("- Add a few benign unrelated resources for realism. Make ids human-readable and unique.\n")
	b.WriteString("- EVERY prowler finding must appear in EITHER a corroboration of a real target OR in inert_findings.\n")
	b.WriteString("Return JSON: {\"inventory\":{...},\"prowler\":[...],\"answer_key\":{...}}\n")
	return b.String()
}

// stripFences removes a leading/trailing ```json ... ``` fence if the model added one.
func stripFences(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "```") {
		if i := strings.IndexByte(s, '\n'); i >= 0 {
			s = s[i+1:]
		}
		s = strings.TrimSuffix(strings.TrimSpace(s), "```")
	}
	return strings.TrimSpace(s)
}
