"use client";

import { useState, useTransition } from "react";
import { Sparkles, Loader2, CircleAlert } from "lucide-react";
import { generateBrief, type Brief } from "@/app/(app)/brief/actions";
import { SeverityBadge } from "@/components/ui/primitives";
import { cn } from "@/lib/utils";

// "Generate plain-English brief" — runs the L2 Lead/translator over the tenant's findings and renders
// the consultant deliverable (exec summary + recommendations + the prioritized issues, in plain English).
export function GenerateBrief() {
  const [pending, start] = useTransition();
  const [brief, setBrief] = useState<Brief | null>(null);

  function run() {
    setBrief(null);
    start(async () => setBrief(await generateBrief()));
  }

  return (
    <div className="space-y-6">
      <div>
        <button
          onClick={run}
          disabled={pending}
          className="inline-flex items-center gap-2 rounded-lg border border-accent/40 bg-accent-soft px-3.5 py-2 text-sm font-medium text-accent transition hover:border-accent disabled:opacity-50"
        >
          {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
          {pending ? "Writing your brief…" : "Generate plain-English brief"}
        </button>
        {pending && (
          <p className="mt-2 text-xs text-faint">
            The AI security engineer is reading your findings and writing the brief — this can take a minute.
          </p>
        )}
      </div>

      {brief?.ok === false && (
        <div className="flex items-center gap-2 rounded-xl border border-critical/40 bg-critical/10 px-4 py-3 text-sm text-critical">
          <CircleAlert className="h-4 w-4" /> {brief.error}
        </div>
      )}

      {brief?.ok && (
        <div className="space-y-5">
          {brief.summary?.executive_summary && (
            <Section title="Executive summary" body={brief.summary.executive_summary} />
          )}
          {brief.summary?.recommendations && (
            <Section title="What to do next" body={brief.summary.recommendations} />
          )}
          {brief.summary?.methodology && <Section title="How we looked" body={brief.summary.methodology} />}

          {(brief.reports?.length ?? 0) > 0 && (
            <div>
              <h3 className="mb-2 text-sm font-semibold text-ink">Prioritized issues</h3>
              <div className="card divide-y divide-border">
                {brief.reports!.map((f) => (
                  <div key={f.id} className="px-5 py-3.5">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-sm font-medium text-ink">{f.title}</span>
                      <SeverityBadge severity={f.severity} />
                    </div>
                    {f.description && <p className="mt-1 text-sm leading-relaxed text-muted">{f.description}</p>}
                    {f.endpoint && <div className="mono mt-1 truncate text-[11px] text-faint">{f.endpoint}</div>}
                  </div>
                ))}
              </div>
            </div>
          )}

          {!brief.summary?.executive_summary && (brief.reports?.length ?? 0) === 0 && (
            <p className="text-sm text-muted">The translator ran but produced no brief — try again, or run a scan first.</p>
          )}
          {brief.model && <p className="text-xs text-faint">Generated by {brief.model}.</p>}
        </div>
      )}
    </div>
  );
}

function Section({ title, body }: { title: string; body: string }) {
  return (
    <div className={cn("rounded-xl border border-border bg-surface p-5")}>
      <h3 className="mb-1.5 text-sm font-semibold text-ink">{title}</h3>
      <p className="whitespace-pre-line text-sm leading-relaxed text-muted">{body}</p>
    </div>
  );
}
